
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tujomckfdircqiztmqxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1am9tY2tmZGlyY3FpenRtcXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3Mjc5MTQsImV4cCI6MjA1NTMwMzkxNH0.58HePWM2rQf3LG5-ydzyWFaylM17bnkCW6rPJjwhH0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (input: RequestInfo | URL, init?: RequestInit) => {
        // Ajout d'un timeout plus long pour éviter les erreurs de connexion
        const fetchOptions: RequestInit = {
          ...init,
          // Si nécessaire, on peut ajouter des options supplémentaires ici
        };
        return fetch(input, fetchOptions);
      },
      headers: {
        'X-Client-Info': 'supabase-js-web/2.33.1',
      },
    },
  }
);
